### ISSUE TITLE
Result always 0s

### ISSUE THREAD

**Issue by Theemuts** [joekain/bmark#12]
I'm trying to benchmark a simple piece of code:

```
defmodule Naming do
  use Bmark

  bmark :with_list, runs: 20 do
    __MODULE__
    |> Module.split
    |> List.last
    |> Macro.underscore
    |> String.to_atom
  end
end
```

The file naming.with_lists.results is created, but the result is always 0. The issue occurs in both Elixir v1.2.3, and v1.3.0-dev. I use Ubuntu 15.10, Erlang 18.3 (hipe enabled).

**Comment by joekain** [comment]
Hi @Theemuts,

I think the problem is that your code is too simple.  It must take less time than the granularity of the timer that bmark is using.  I guess one thing you could try would be to run that function multiple times within the `bmark` block.

That said, bmark is best suited to benchmarking your entire system rather than small functions like this.  The idea being that you run a known workload through your system and measure the time spent (usually in 10s of seconds or even minutes).  Then, based on profiling make a change to functions that contribute significantly to the overall runtime and finally rerun the benchmark to determine what impact your changes have had.

You might find that [benchfella](https://github.com/alco/benchfella) is a better tool for measuring small functions like the one in your example.

**Comment by Theemuts** [comment]
Hi @joekain,

Thanks for your reply. I wrote this code as an initial test, I'm planning to benchmark bigger pieces of code. Unfortunately, even after extending my code to the following:

```
defmodule Naming do
  use Bmark

  bmark :with_list, runs: 1 do
    tuple = {Alpha, Beta, Gamma, Delta, Epsilon, Zeta, Eta, Theta, Iota, Kappa, Lambda, Mu, Nu, Ksi, Omicron, Pi, Rho, Sigma, Tau, Upsilon, Phi, Chi, Psi, Omega}
    n = tuple_size tuple

    Enum.map(1..1000000, fn _ ->
      Enum.map([0, 0, 0, 0], fn _ ->
        index = :rand.uniform(n)
        elem(tuple, index - 1)
      end)
      |> Enum.reduce(fn (x, acc) -> Module.concat(x, acc) end)
      |> Module.split
      |> List.last
      |> Macro.underscore
      |> String.to_atom
    end)
  end
end
```

which takes over 15 seconds to complete once, the result remains equal to 0.

**Comment by joekain** [comment]
Hi @Theemuts,

Ah ok, that's no good.  I'll take a look at this (probably tomorrow) and will see if I can fix it.

**Comment by Theemuts** [comment]
Thanks @joekain! If you need me to check anything for you, please let me
know.
Op 19 mrt. 2016 8:39 PM schreef "Joseph Kain" notifications@github.com:

**Comment by joekain** [comment]
Ok, I'm getting result of 1 millisecond when I run your test.  It's not 0 but its not right either given that test took about 13 seconds to run.  I'll continue to investigate.

**Comment by joekain** [comment]
It looks the do block passed to `bmark` is being evaluated when the `bmark` macro is evaluated rather than at program exit when the timer is run.  The timer is just monitoring an empty function.  I don't understand why this is happening but something must be wrong with the `bmark` macro itself.  I'll look into this next.

**Comment by joekain** [comment]
@Theemuts, this should be fixed now.  Can you verify the fix only your system and with your project(s).  Once you do that I'll create a new bmark release.  You can run against master by writing the dependency in mix.exs like this:

```
{:bmark, git: "/Users/jkain/Documents/Projects/elixir/bmark", branch: "master"}
```

**Comment by Theemuts** [comment]
It works perfectly. I set it to perform four runs, and I got results in the range of 13.4 to 13.6 seconds as expected. Thank you for the fix, @joekain!

**Comment by joekain** [comment]
Great, thanks for checking that @Theemuts.  Version 1.0.3, with this fix, should be published to hex.pm now.

**Comment by Theemuts** [comment]
Works perfectly, thanks!
